project_id = "wxekpbmapcugbyqtklva"

[functions.generate-content]
verify_jwt = false

[functions.generate-text]
verify_jwt = false

[functions.generate-slides]
verify_jwt = false

[functions.backup-database]
verify_jwt = false

[functions.restore-database]
verify_jwt = false

[functions.generate-deck]
verify_jwt = false

[functions.generate-slide-image]
verify_jwt = false

[functions.ai-slide-assist]
verify_jwt = false
